export const data = {
  layout: {
    statuses: [
      { id: '13', x: 652, y: 80, name: 'Новая', type: 0 },
      { id: '14', x: 954, y: 106, name: 'В работе', type: 1 },
      { id: '15', x: 719, y: 537, name: 'Подготовка КП', type: 1 },
      { id: '16', x: 826, y: 227, name: 'Обработка возражений', type: 1 },
      { id: '17', x: 985, y: 411, name: 'Подготовка договора', type: 1 },
      { id: '18', x: 524, y: 337, name: 'Подписание договора', type: 1 },
      { id: '19', x: 949, y: 165, name: 'Настройка интеграций', type: 1 },
      { id: '20', x: 846, y: 353, name: 'Тестирование', type: 1 },
      { id: '21', x: 515, y: 536, name: 'Успешно реализовано', type: 2 },
      { id: '22', x: 507, y: 204, name: 'Закрыто/Не реализовано', type: 2 },
      { id: '23', x: 1000, y: 284, name: 'Отмена', type: 2 },
    ],
    transitions: [
      {
        id: '26',
        sourceAngle: null,
        targetAngle: null,
        sourceId: '13',
        targetId: '14',
      },
      {
        id: '27',
        sourceAngle: null,
        targetAngle: null,
        sourceId: '13',
        targetId: '23',
      },
      {
        id: '28',
        sourceAngle: null,
        targetAngle: null,
        sourceId: '14',
        targetId: '15',
      },
      {
        id: '29',
        sourceAngle: null,
        targetAngle: null,
        sourceId: '14',
        targetId: '23',
      },
      {
        id: '30',
        sourceAngle: null,
        targetAngle: null,
        sourceId: '15',
        targetId: '16',
      },
      {
        id: '31',
        sourceAngle: null,
        targetAngle: null,
        sourceId: '15',
        targetId: '17',
      },
      {
        id: '33',
        sourceAngle: null,
        targetAngle: null,
        sourceId: '17',
        targetId: '18',
      },
      {
        id: '35',
        sourceAngle: null,
        targetAngle: null,
        sourceId: '18',
        targetId: '19',
      },
      {
        id: '37',
        sourceAngle: null,
        targetAngle: null,
        sourceId: '19',
        targetId: '20',
      },
      {
        id: '39',
        sourceAngle: null,
        targetAngle: null,
        sourceId: '20',
        targetId: '21',
      },
      {
        id: '41',
        sourceAngle: null,
        targetAngle: null,
        sourceId: '16',
        targetId: '17',
      },
      {
        id: '40',
        sourceAngle: null,
        targetAngle: null,
        sourceId: '20',
        targetId: '22',
      },
      {
        id: '42',
        sourceAngle: null,
        targetAngle: null,
        sourceId: '16',
        targetId: '22',
      },
      {
        id: '36',
        sourceAngle: null,
        targetAngle: null,
        sourceId: '18',
        targetId: '22',
      },
      {
        id: '38',
        sourceAngle: null,
        targetAngle: null,
        sourceId: '19',
        targetId: '22',
      },
      {
        id: '32',
        sourceAngle: null,
        targetAngle: null,
        sourceId: '15',
        targetId: '22',
      },
      {
        id: '34',
        sourceAngle: null,
        targetAngle: null,
        sourceId: '17',
        targetId: '22',
      },
    ],
  },
}
